from PyQt5 import QtCore, QtGui, QtWidgets
from utils.pyTask import PyTask
from utils import date

class taskWidget(QtWidgets.QWidget):
    def __init__(self, task=PyTask()):
        super().__init__()
        self.setupUi(task)

    def setupUi(self, task):
        self.setObjectName("tab")
        self.taskSpec = QtWidgets.QGroupBox(self)
        self.taskSpec.setGeometry(QtCore.QRect(10, 0, 371, 311))
        self.taskSpec.setObjectName("taskSpec")

        self.formLayoutWidget = QtWidgets.QWidget(self.taskSpec)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 342, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")

        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)

        self.lbl_Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Label.setText(task.label)
        self.lbl_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Label.setObjectName("lbl_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_Label)

        self.deadline = QtWidgets.QLabel(self.formLayoutWidget)
        self.deadline.setObjectName("deadline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.deadline)

        self.require = QtWidgets.QLabel(self.formLayoutWidget)
        self.require.setObjectName("require")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.require)

        self.type = QtWidgets.QLabel(self.formLayoutWidget)
        self.type.setObjectName("type")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.type)

        self.co_work = QtWidgets.QLabel(self.formLayoutWidget)
        self.co_work.setObjectName("co_work")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.co_work)

        self.description = QtWidgets.QLabel(self.formLayoutWidget)
        self.description.setObjectName("description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.description)

        self.lbl_Deadline = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Deadline.setText(task.deadline)
        self.lbl_Deadline.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Deadline.setObjectName("lbl_Deadline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_Deadline)

        self.browse_description = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.browse_description.setObjectName("browse_description")
        self.browse_description.setPlainText(task.description)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.browse_description)

        self.lbl_ReqTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_ReqTime.setText(task.require)
        self.lbl_ReqTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ReqTime.setObjectName("lbl_ReqTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_ReqTime)

        self.lbl_Type = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Type.setText(task.type)
        self.lbl_Type.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Type.setObjectName("lbl_Type")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_Type)

        self.lbl_CoWork = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_CoWork.setText(str(task.co_work))
        self.lbl_CoWork.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_CoWork.setObjectName("lbl_CoWork")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_CoWork)

        # Show Remain Time
        """
        #   SHOW TIME LEFT FOR DEADLINE.
        """
        self.remainTime = QtWidgets.QGroupBox(self)
        self.remainTime.setGeometry(QtCore.QRect(10, 320, 601, 161))
        self.remainTime.setObjectName("remainTime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.remainTime)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 581, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd_Day = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Day.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Day.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Day.setSmallDecimalPoint(False)
        self.lcd_Day.setDigitCount(2)
        self.lcd_Day.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Day.setProperty("value", 0.0)
        self.lcd_Day.setObjectName("lcd_Day")
        self.horizontalLayout.addWidget(self.lcd_Day)
        self.label_day = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_day.setFont(font)
        self.label_day.setScaledContents(False)
        self.label_day.setAlignment(QtCore.Qt.AlignCenter)
        self.label_day.setWordWrap(False)
        self.label_day.setObjectName("label_day")
        self.horizontalLayout.addWidget(self.label_day)
        self.lcd_Hour = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Hour.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Hour.setSmallDecimalPoint(False)
        self.lcd_Hour.setDigitCount(2)
        self.lcd_Hour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Hour.setProperty("value", 0.0)
        self.lcd_Hour.setObjectName("lcd_Day")
        self.horizontalLayout.addWidget(self.lcd_Hour)
        self.label_hour = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_hour.setFont(font)
        self.label_hour.setScaledContents(False)
        self.label_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hour.setWordWrap(False)
        self.label_hour.setObjectName("label_hour")
        self.horizontalLayout.addWidget(self.label_hour)
        self.lcd_Min = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Min.setSmallDecimalPoint(False)
        self.lcd_Min.setDigitCount(2)
        self.lcd_Min.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Min.setProperty("value", 0.0)
        self.lcd_Min.setObjectName("lcd_Min")
        self.horizontalLayout.addWidget(self.lcd_Min)
        self.label_min = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_min.setFont(font)
        self.label_min.setScaledContents(False)
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setWordWrap(False)
        self.label_min.setObjectName("label_min")
        self.horizontalLayout.addWidget(self.label_min)
        self.btn_edit = QtWidgets.QPushButton(self)
        self.btn_edit.setGeometry(QtCore.QRect(520, 20, 93, 28))
        self.btn_edit.setObjectName("btn_edit")

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.taskSpec.setTitle(_translate("MainWindow", "Specs"))
        self.label.setText(_translate("MainWindow", "제목"))
        self.deadline.setText(_translate("MainWindow", "제출기한"))
        self.require.setText(_translate("MainWindow", "필요 시간"))
        self.type.setText(_translate("MainWindow", "분류"))
        self.co_work.setText(_translate("MainWindow", "팀과제"))
        self.description.setText(_translate("MainWindow", "설명"))
        self.remainTime.setTitle(_translate("MainWindow", "제출까지 남은 시간:"))
        self.label_day.setText(_translate("MainWindow", "일"))
        self.label_hour.setText(_translate("MainWindow", "시간"))
        self.label_min.setText(_translate("MainWindow", "분"))
        self.btn_edit.setText(_translate("MainWindow", "수정"))