# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 587)
        MainWindow.setMinimumSize(QtCore.QSize(670, 400))
        MainWindow.setMaximumSize(QtCore.QSize(670, 800))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 30, 671, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, 10, 661, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.taskTable = QtWidgets.QTableWidget(self.frame)
        self.taskTable.setGeometry(QtCore.QRect(10, 10, 531, 476))
        self.taskTable.setMinimumSize(QtCore.QSize(0, 0))
        self.taskTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.taskTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.taskTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.taskTable.setShowGrid(True)
        self.taskTable.setWordWrap(False)
        self.taskTable.setCornerButtonEnabled(True)
        self.taskTable.setRowCount(23)
        self.taskTable.setColumnCount(4)
        self.taskTable.setObjectName("taskTable")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.taskTable.setHorizontalHeaderItem(3, item)
        self.taskTable.horizontalHeader().setCascadingSectionResizes(True)
        self.taskTable.horizontalHeader().setDefaultSectionSize(120)
        self.delButton = QtWidgets.QPushButton(self.frame)
        self.delButton.setGeometry(QtCore.QRect(550, 60, 93, 28))
        self.delButton.setObjectName("delButton")
        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(550, 20, 93, 28))
        self.addButton.setObjectName("addButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.taskTabs = QtWidgets.QTabWidget(self.page_2)
        self.taskTabs.setGeometry(QtCore.QRect(10, 10, 651, 501))
        self.taskTabs.setMinimumSize(QtCore.QSize(651, 501))
        self.taskTabs.setMaximumSize(QtCore.QSize(651, 501))
        self.taskTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.taskTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.taskTabs.setElideMode(QtCore.Qt.ElideNone)
        self.taskTabs.setDocumentMode(False)
        self.taskTabs.setTabsClosable(False)
        self.taskTabs.setMovable(True)
        self.taskTabs.setTabBarAutoHide(False)
        self.taskTabs.setObjectName("taskTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.taskSpec = QtWidgets.QGroupBox(self.tab)
        self.taskSpec.setGeometry(QtCore.QRect(10, 0, 371, 311))
        self.taskSpec.setObjectName("taskSpec")
        self.formLayoutWidget = QtWidgets.QWidget(self.taskSpec)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 342, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lbl_Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Label.setText("")
        self.lbl_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Label.setObjectName("lbl_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_Label)
        self.deadline = QtWidgets.QLabel(self.formLayoutWidget)
        self.deadline.setObjectName("deadline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.deadline)
        self.require = QtWidgets.QLabel(self.formLayoutWidget)
        self.require.setObjectName("require")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.require)
        self.type = QtWidgets.QLabel(self.formLayoutWidget)
        self.type.setObjectName("type")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.type)
        self.co_work = QtWidgets.QLabel(self.formLayoutWidget)
        self.co_work.setObjectName("co_work")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.co_work)
        self.description = QtWidgets.QLabel(self.formLayoutWidget)
        self.description.setObjectName("description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.description)
        self.lbl_Deadline = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Deadline.setText("")
        self.lbl_Deadline.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Deadline.setObjectName("lbl_Deadline")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_Deadline)
        self.browse_description = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.browse_description.setObjectName("browse_description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.browse_description)
        self.lbl_ReqTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_ReqTime.setText("")
        self.lbl_ReqTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ReqTime.setObjectName("lbl_ReqTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_ReqTime)
        self.lbl_Type = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Type.setText("")
        self.lbl_Type.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Type.setObjectName("lbl_Type")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_Type)
        self.lbl_CoWork = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_CoWork.setText("")
        self.lbl_CoWork.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_CoWork.setObjectName("lbl_CoWork")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_CoWork)
        self.remainTime = QtWidgets.QGroupBox(self.tab)
        self.remainTime.setGeometry(QtCore.QRect(10, 320, 601, 161))
        self.remainTime.setObjectName("remainTime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.remainTime)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 581, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd_Hour = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Hour.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Hour.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Hour.setSmallDecimalPoint(False)
        self.lcd_Hour.setDigitCount(2)
        self.lcd_Hour.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Hour.setProperty("value", 0.0)
        self.lcd_Hour.setObjectName("lcd_Hour")
        self.horizontalLayout.addWidget(self.lcd_Hour)
        self.label_day = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_day.setFont(font)
        self.label_day.setScaledContents(False)
        self.label_day.setAlignment(QtCore.Qt.AlignCenter)
        self.label_day.setWordWrap(False)
        self.label_day.setObjectName("label_day")
        self.horizontalLayout.addWidget(self.label_day)
        self.lcd_Day = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Day.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Day.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Day.setSmallDecimalPoint(False)
        self.lcd_Day.setDigitCount(2)
        self.lcd_Day.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Day.setProperty("value", 0.0)
        self.lcd_Day.setObjectName("lcd_Day")
        self.horizontalLayout.addWidget(self.lcd_Day)
        self.label_hour = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_hour.setFont(font)
        self.label_hour.setScaledContents(False)
        self.label_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hour.setWordWrap(False)
        self.label_hour.setObjectName("label_hour")
        self.horizontalLayout.addWidget(self.label_hour)
        self.lcd_Min = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_Min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_Min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_Min.setSmallDecimalPoint(False)
        self.lcd_Min.setDigitCount(2)
        self.lcd_Min.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_Min.setProperty("value", 0.0)
        self.lcd_Min.setObjectName("lcd_Min")
        self.horizontalLayout.addWidget(self.lcd_Min)
        self.label_min = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(44)
        self.label_min.setFont(font)
        self.label_min.setScaledContents(False)
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setWordWrap(False)
        self.label_min.setObjectName("label_min")
        self.horizontalLayout.addWidget(self.label_min)
        self.btn_edit = QtWidgets.QPushButton(self.tab)
        self.btn_edit.setGeometry(QtCore.QRect(520, 20, 93, 28))
        self.btn_edit.setObjectName("btn_edit")
        self.taskTabs.addTab(self.tab, "")
        self.stackedWidget.addWidget(self.page_2)
        self.btn_nextPage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nextPage.setGeometry(QtCore.QRect(560, 0, 81, 28))
        self.btn_nextPage.setObjectName("btn_nextPage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 26))
        self.menubar.setObjectName("menubar")
        self.filemenu = QtWidgets.QMenu(self.menubar)
        self.filemenu.setObjectName("filemenu")
        self.viewmenu = QtWidgets.QMenu(self.menubar)
        self.viewmenu.setObjectName("viewmenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.viewCoWork = QtWidgets.QAction(MainWindow)
        self.viewCoWork.setCheckable(True)
        self.viewCoWork.setObjectName("viewCoWork")
        self.filemenu.addAction(self.actionSave)
        self.viewmenu.addAction(self.viewCoWork)
        self.menubar.addAction(self.filemenu.menuAction())
        self.menubar.addAction(self.viewmenu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.taskTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "과제독촉기"))
        self.taskTable.setSortingEnabled(False)
        item = self.taskTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "이름"))
        item = self.taskTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "제출기한"))
        item = self.taskTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "필요시간"))
        item = self.taskTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "분류"))
        self.delButton.setText(_translate("MainWindow", "삭제"))
        self.addButton.setText(_translate("MainWindow", "추가"))
        self.taskSpec.setTitle(_translate("MainWindow", "Specs"))
        self.label.setText(_translate("MainWindow", "제목"))
        self.deadline.setText(_translate("MainWindow", "제출기한"))
        self.require.setText(_translate("MainWindow", "필요 시간"))
        self.type.setText(_translate("MainWindow", "분류"))
        self.co_work.setText(_translate("MainWindow", "팀과제"))
        self.description.setText(_translate("MainWindow", "설명"))
        self.remainTime.setTitle(_translate("MainWindow", "제출까지 남은 시간:"))
        self.label_day.setText(_translate("MainWindow", "일"))
        self.label_hour.setText(_translate("MainWindow", "시간"))
        self.label_min.setText(_translate("MainWindow", "분"))
        self.btn_edit.setText(_translate("MainWindow", "수정"))
        self.taskTabs.setTabText(self.taskTabs.indexOf(self.tab), _translate("MainWindow", "tab1"))
        self.btn_nextPage.setText(_translate("MainWindow", "NEXT>>"))
        self.filemenu.setTitle(_translate("MainWindow", "File"))
        self.viewmenu.setTitle(_translate("MainWindow", "View"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.viewCoWork.setText(_translate("MainWindow", "CoWork Only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
